CREATE DATABASE CRUD_LOGIN;
USE CRUD_LOGIN;


CREATE TABLE REGISTROS(
 USUARIO VARCHAR (100) NOT NULL , 
 CONTRASEÑA VARCHAR (100),
 ROLL VARCHAR (100),
 PRIMARY KEY (USUARIO),
 );

 INSERT INTO REGISTROS VALUES ('LISBETH','1230','ADMINISTRADOR');
 INSERT INTO REGISTROS VALUES ('MARIANO','1705','CLIENTE');
 INSERT INTO REGISTROS VALUES ('FERNANDA','4978','SECRETARIA');



CREATE TABLE DATOS(
ID_USUARIO INT NOT NULL PRIMARY KEY,
NOMBRE VARCHAR (100),
PAIS VARCHAR (100),
OCUPACION VARCHAR (100),
CORREO VARCHAR (100),
);

DROP TABLE DATOS;

INSERT INTO DATOS(ID_USUARIO,NOMBRE,PAIS,OCUPACION,CORREO)VALUES (01,'LISBETH','GUATEMALA','ADMINSTRADOR','LISBETH.PAREDES@GMAIL.COM');
INSERT INTO DATOS(ID_USUARIO,NOMBRE,PAIS,OCUPACION,CORREO)VALUES (02,'DAVID','MEXICO','SECRETARIO','DAVID.05@GMAIL.COM');
INSERT INTO DATOS(ID_USUARIO,NOMBRE,PAIS,OCUPACION,CORREO)VALUES (03,'SANTIAGO','HONDURAS','CLIENTE','SANTI.AGO@GMAIL.COM');
INSERT INTO DATOS(ID_USUARIO,NOMBRE,PAIS,OCUPACION,CORREO)VALUES (04,'FERNANDO','COLOMBIA','CLIENTE','FERNANDOCOLOMBIA@GMAIL.COM');
INSERT INTO DATOS(ID_USUARIO,NOMBRE,PAIS,OCUPACION,CORREO)VALUES (05,'VENJAMIN','GUATEMALA','SECRETARIO','VENJAMIN21@GMAIL.COM');

SELECT * FROM DATOS;